name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        houdini-version:
          - "19.5"  # Python 3.9
          # - "20.0"  # Python 3.10

    container:
      image: captainhammy/hython-runner:${{ matrix.houdini-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Unit Tests

      - name: Install unit test dependencies
        run: python -m pip install tox tox-gh-actions

      - name: Test with tox
        run: tox

      # Integration tests

      - name: Build package
        uses: captainhammy/build-rez-package-action@v1.0
        with:
          package_root: ./tests/test_package

      - name: Test package with default test name
        id: run_default_test
        uses: ./
        with:
          package_root: ./tests/test_package

      - run:   echo "$OUTPUTS"
        shell: bash
        env:
         OUTPUTS: ${{ toJSON(steps.run_default_test.outputs) }}

      - name: Fail if default test not ran
        shell: bash
        if: steps.run_default_test.outputs.package_test_ran != 1
        run: exit 1

      - name: Test package with specific test name
        id: run_specific_test
        uses: ./
        with:
          test_name: specific
          package_root: ./tests/test_package

      - run:   echo "$OUTPUTS"
        shell: bash
        env:
         OUTPUTS: ${{ toJSON(steps.run_specific_test.outputs) }}

      - name: Fail if the specific test not ran
        shell: bash
        if: steps.run_specific_test.outputs.package_test_ran != 1
        run: exit 1
