name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        houdini-version: ["20.5", "21.0"]

    container:
      image: captainhammy/hython-runner:${{ matrix.houdini-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      # Unit Tests

      - name: Install unit test dependencies
        run: | 
          python3 -m pip install --upgrade pip
          python3 -m pip install --group github

      # Run static analysis tox tests
      - name: Test with tox (static)
        run: tox -m static

      # Run unit tests with tox
      - name: Test with tox (tests)
        run: tox -m test

      # Integration tests

      - name: Build package
        uses: captainhammy/build-rez-package-action@v1
        with:
          package_root: ./tests/test_package

      - name: Test package with default test name
        id: run_default_test
        uses: ./
        env:
          TEST_FILE: ${{ runner.temp }}/results/unit.txt
        with:
          package_root: ./tests/test_package

      - name: Verify default (unit) test ran
        env:
          TEST_FILE: ${{ runner.temp }}/results/unit.txt
        run: |
          if ! test -f $TEST_FILE; then
            exit 1
          fi

      - name: Test package with specific test name
        id: run_specific_test
        uses: ./
        env:
          TEST_FILE: ${{ runner.temp }}/results/specific.txt
        with:
          test_name: specific
          package_root: ./tests/test_package

      - name: Verify the specific test ran
        env:
          TEST_FILE: ${{ runner.temp }}/results/specific.txt
        run: |
          if ! test -f $TEST_FILE; then
            exit 1
          fi
