name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        houdini-version:
          - "19.5"
          - "20.0"
          - "20.5"

    container:
      image: captainhammy/hython-runner:${{ matrix.houdini-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Unit Tests

      - name: Install unit test dependencies
        run: python -m pip install tox tox-gh-actions

      - name: Test with tox
        run: tox

      # Integration tests

      - name: Build package
        uses: captainhammy/build-rez-package-action@v1
        with:
          package_root: ./tests/test_package

      - name: Test package with default test name
        id: run_default_test
        uses: ./
        env:
          TEST_TEMP_DIR: ${{ runner.temp }}/results
        with:
          package_root: ./tests/test_package

      - name: Verify default (unit) test ran
        env:
          TEST_FILE: ${{ runner.temp }}/results/unit.txt
        run: |
          if ! test -f $TEST_FILE; then
            exit 1
          fi
      - name: Test package with specific test name
        id: run_specific_test
        uses: ./
        env:
          TEST_TEMP_DIR: ${{ runner.temp }}/results
        with:
          test_name: specific
          package_root: ./tests/test_package

      - name: Verify the specific test ran
        env:
          TEST_FILE: ${{ runner.temp }}/results/specific.txt
        run: |
          if ! test -f $TEST_FILE; then
            exit 1
          fi
